version: 2

updates:
  - package-ecosystem: "terraform"
    schedule:
      directory: '/'
      interval: "daily"
    open-pull-requests-limit: 3
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
